import { NextRequest, NextResponse } from 'next/server';

export async function POST(request: NextRequest) {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    return NextResponse.json({ error: 'Gemini API key not configured' }, { status: 500 });
  }

  const formData = await request.formData();
  const prompt = formData.get('prompt') as string;
  const images = formData.getAll('image[]') as File[];

  // Convert uploaded images to base64 inline_data parts
  const imageParts = await Promise.all(
    images.map(async (img) => {
      const buffer = Buffer.from(await img.arrayBuffer());
      const base64 = buffer.toString('base64');
      const mimeType = img.type || 'image/jpeg';
      return {
        inline_data: {
          mime_type: mimeType,
          data: base64,
        },
      };
    })
  );

  const body = {
    contents: [
      {
        role: 'user',
        parts: [
          // Reference images first, then the prompt.
          ...imageParts,
          { text: prompt },
        ],
      },
    ],
    generationConfig: {
      responseModalities: ['TEXT', 'IMAGE'],
      imageConfig: {
        // Wizard uses square previews by default
        aspectRatio: '1:1',
        imageSize: '512',
      },
    },
  };

  // "Nano Banana" image generation models (Gemini API)
  // https://ai.google.dev/gemini-api/docs/image-generation
  const preferredModel =
    process.env.GEMINI_IMAGE_MODEL?.trim() ||
    'gemini-2.5-flash-image';

  const modelFallbacks = [
    preferredModel,
    'gemini-3.1-flash-image-preview',
    'gemini-3-pro-image-preview',
  ];

  const callModel = async (model: string) => {
    const url = `https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent`;
    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), 60_000);
    try {
      return await fetch(url, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'x-goog-api-key': apiKey,
        },
        body: JSON.stringify(body),
        signal: controller.signal,
      });
    } finally {
      clearTimeout(timeout);
    }
  };

  let resp: Response | null = null;
  let lastErrText = '';
  let lastStatus = 500;
  let usedModel = preferredModel;

  for (const model of modelFallbacks) {
    usedModel = model;
    resp = await callModel(model);
    lastStatus = resp.status;
    if (resp.ok) break;
    lastErrText = await resp.text().catch(() => '');
    // try next model on "not found" / "not supported"
    if (resp.status === 404 || resp.status === 400) continue;
    break;
  }

  // Retry once on rate limit
  if (resp && resp.status === 429) {
    await new Promise((r) => setTimeout(r, 10_000));
    resp = await callModel(usedModel);
  }

  if (!resp || !resp.ok) {
    const errText = resp ? (await resp.text().catch(() => lastErrText)) : lastErrText;
    return NextResponse.json(
      {
        error: errText || 'Gemini request failed',
        model: usedModel,
        status: resp?.status ?? lastStatus,
      },
      { status: resp?.status ?? lastStatus }
    );
  }

  const data = await resp.json();

  // Extract the generated image from Gemini's response
  const candidates = data.candidates || [];
  for (const candidate of candidates) {
    const parts = candidate.content?.parts || [];
    for (const part of parts) {
      const inline = part.inline_data || part.inlineData;
      if (inline) {
        // Return in the same format as the OpenAI route for compatibility
        return NextResponse.json({
          data: [{ b64_json: inline.data }],
          model: usedModel,
        });
      }
    }
  }

  return NextResponse.json(
    { error: 'No image generated by Gemini', raw: data, model: usedModel },
    { status: 500 }
  );
}
